package com.whut.equipmanage.dataobject;

public class AdminDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_id
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_name
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.phone_num
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    private String phoneNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_id
     *
     * @return the value of t_admin.admin_id
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_id
     *
     * @param adminId the value for t_admin.admin_id
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_name
     *
     * @return the value of t_admin.admin_name
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_name
     *
     * @param adminName the value for t_admin.admin_name
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.phone_num
     *
     * @return the value of t_admin.phone_num
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.phone_num
     *
     * @param phoneNum the value for t_admin.phone_num
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }
}