package com.whut.equipmanage.dataobject;

import java.util.Date;

public class CheckDO extends CheckDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.check_time
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.worker_id
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    private Integer workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.note
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.check_time
     *
     * @return the value of t_check.check_time
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.check_time
     *
     * @param checkTime the value for t_check.check_time
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.worker_id
     *
     * @return the value of t_check.worker_id
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.worker_id
     *
     * @param workerId the value for t_check.worker_id
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.note
     *
     * @return the value of t_check.note
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.note
     *
     * @param note the value for t_check.note
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}