package com.whut.equipmanage.dataobject;

public class CheckDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.equip_id
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    private Integer equipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.detai_ild
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    private Integer detaiIld;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.equip_id
     *
     * @return the value of t_check.equip_id
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.equip_id
     *
     * @param equipId the value for t_check.equip_id
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.detai_ild
     *
     * @return the value of t_check.detai_ild
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public Integer getDetaiIld() {
        return detaiIld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.detai_ild
     *
     * @param detaiIld the value for t_check.detai_ild
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public void setDetaiIld(Integer detaiIld) {
        this.detaiIld = detaiIld;
    }
}