package com.whut.equipmanage.dataobject;

import java.util.Date;

public class CheckDO extends CheckDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.check_time
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    private Date checkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.checker
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    private String checker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.team
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    private String team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_check.note
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.check_time
     *
     * @return the value of t_check.check_time
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public Date getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.check_time
     *
     * @param checkTime the value for t_check.check_time
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public void setCheckTime(Date checkTime) {
        this.checkTime = checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.checker
     *
     * @return the value of t_check.checker
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public String getChecker() {
        return checker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.checker
     *
     * @param checker the value for t_check.checker
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public void setChecker(String checker) {
        this.checker = checker == null ? null : checker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.team
     *
     * @return the value of t_check.team
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.team
     *
     * @param team the value for t_check.team
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_check.note
     *
     * @return the value of t_check.note
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_check.note
     *
     * @param note the value for t_check.note
     *
     * @mbg.generated Sun Dec 13 14:11:56 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}