package com.whut.equipmanage.dataobject;

public class LocationDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.equi_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private Integer equiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.longitude
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.latitude
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.equi_id
     *
     * @return the value of t_location.equi_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public Integer getEquiId() {
        return equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.equi_id
     *
     * @param equiId the value for t_location.equi_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setEquiId(Integer equiId) {
        this.equiId = equiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.longitude
     *
     * @return the value of t_location.longitude
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.longitude
     *
     * @param longitude the value for t_location.longitude
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.latitude
     *
     * @return the value of t_location.latitude
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.latitude
     *
     * @param latitude the value for t_location.latitude
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }
}