package com.whut.equipmanage.dataobject;

import com.whut.equipmanage.common.resultBean.Order;

import java.util.Date;

public class OrderDO {

    public OrderDO(Integer workerId, String workClass,String instruction){
        this.workerId = workerId;
        this.workClass = workClass;
        this.instruction = instruction;
        this.initTime = new Date();
        this.status = "0";
    }

    public OrderDO(){}
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.init_time
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    private Date initTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.work_class
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    private String workClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.instruction
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    private String instruction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.worker_id
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    private Integer workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.publisher
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    private Integer publisher;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.init_time
     *
     * @return the value of t_order.init_time
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public Date getInitTime() {
        return initTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.init_time
     *
     * @param initTime the value for t_order.init_time
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public void setInitTime(Date initTime) {
        this.initTime = initTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.work_class
     *
     * @return the value of t_order.work_class
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public String getWorkClass() {
        return workClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.work_class
     *
     * @param workClass the value for t_order.work_class
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public void setWorkClass(String workClass) {
        this.workClass = workClass == null ? null : workClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.instruction
     *
     * @return the value of t_order.instruction
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.instruction
     *
     * @param instruction the value for t_order.instruction
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.worker_id
     *
     * @return the value of t_order.worker_id
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.worker_id
     *
     * @param workerId the value for t_order.worker_id
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.publisher
     *
     * @return the value of t_order.publisher
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public Integer getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.publisher
     *
     * @param publisher the value for t_order.publisher
     *
     * @mbg.generated Tue Dec 15 15:01:22 CST 2020
     */
    public void setPublisher(Integer publisher) {
        this.publisher = publisher;
    }
}