package com.whut.equipmanage.dataobject;

import java.util.Date;

public class OrderDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.equip_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private Integer equipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.init_time
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private Date initTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.class
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.team
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String team;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.instruction
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String instruction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.equip_id
     *
     * @return the value of t_order.equip_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.equip_id
     *
     * @param equipId the value for t_order.equip_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.init_time
     *
     * @return the value of t_order.init_time
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public Date getInitTime() {
        return initTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.init_time
     *
     * @param initTime the value for t_order.init_time
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setInitTime(Date initTime) {
        this.initTime = initTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.class
     *
     * @return the value of t_order.class
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getClass() {
        return class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.class
     *
     * @param class the value for t_order.class
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setClass(String class) {
        this.class = class == null ? null : class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.team
     *
     * @return the value of t_order.team
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getTeam() {
        return team;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.team
     *
     * @param team the value for t_order.team
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setTeam(String team) {
        this.team = team == null ? null : team.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.instruction
     *
     * @return the value of t_order.instruction
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getInstruction() {
        return instruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.instruction
     *
     * @param instruction the value for t_order.instruction
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setInstruction(String instruction) {
        this.instruction = instruction == null ? null : instruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}