package com.whut.equipmanage.dataobject;

import java.util.Date;

public class ProcessLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.order_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.equip_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    private Integer equipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.time_start
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    private Date timeStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.time_end
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    private Date timeEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.note
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.worker_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    private Integer workerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.order_id
     *
     * @return the value of t_process_log.order_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.order_id
     *
     * @param orderId the value for t_process_log.order_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.equip_id
     *
     * @return the value of t_process_log.equip_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.equip_id
     *
     * @param equipId the value for t_process_log.equip_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.time_start
     *
     * @return the value of t_process_log.time_start
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public Date getTimeStart() {
        return timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.time_start
     *
     * @param timeStart the value for t_process_log.time_start
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.time_end
     *
     * @return the value of t_process_log.time_end
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.time_end
     *
     * @param timeEnd the value for t_process_log.time_end
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.note
     *
     * @return the value of t_process_log.note
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.note
     *
     * @param note the value for t_process_log.note
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.worker_id
     *
     * @return the value of t_process_log.worker_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.worker_id
     *
     * @param workerId the value for t_process_log.worker_id
     *
     * @mbg.generated Tue Dec 15 15:21:03 CST 2020
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }
}