package com.whut.equipmanage.dataobject;

import java.util.Date;

public class ProcessLogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.log_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.equip_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private Integer equipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.trans_from
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String transFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.trans_to
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String transTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.time_start
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private Date timeStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.time_end
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private Date timeEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_process_log.note
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.log_id
     *
     * @return the value of t_process_log.log_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.log_id
     *
     * @param logId the value for t_process_log.log_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.equip_id
     *
     * @return the value of t_process_log.equip_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.equip_id
     *
     * @param equipId the value for t_process_log.equip_id
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.trans_from
     *
     * @return the value of t_process_log.trans_from
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getTransFrom() {
        return transFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.trans_from
     *
     * @param transFrom the value for t_process_log.trans_from
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setTransFrom(String transFrom) {
        this.transFrom = transFrom == null ? null : transFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.trans_to
     *
     * @return the value of t_process_log.trans_to
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getTransTo() {
        return transTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.trans_to
     *
     * @param transTo the value for t_process_log.trans_to
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setTransTo(String transTo) {
        this.transTo = transTo == null ? null : transTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.time_start
     *
     * @return the value of t_process_log.time_start
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public Date getTimeStart() {
        return timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.time_start
     *
     * @param timeStart the value for t_process_log.time_start
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setTimeStart(Date timeStart) {
        this.timeStart = timeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.time_end
     *
     * @return the value of t_process_log.time_end
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public Date getTimeEnd() {
        return timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.time_end
     *
     * @param timeEnd the value for t_process_log.time_end
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setTimeEnd(Date timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_process_log.note
     *
     * @return the value of t_process_log.note
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_process_log.note
     *
     * @param note the value for t_process_log.note
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}