package com.whut.equipmanage.dataobject;

public class WorkerDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_worker.worker_id
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    private Integer workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_worker.worker_name
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    private String workerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_worker.worker_phone
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    private String workerPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_worker.worker_id
     *
     * @return the value of t_worker.worker_id
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_worker.worker_id
     *
     * @param workerId the value for t_worker.worker_id
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_worker.worker_name
     *
     * @return the value of t_worker.worker_name
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public String getWorkerName() {
        return workerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_worker.worker_name
     *
     * @param workerName the value for t_worker.worker_name
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public void setWorkerName(String workerName) {
        this.workerName = workerName == null ? null : workerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_worker.worker_phone
     *
     * @return the value of t_worker.worker_phone
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public String getWorkerPhone() {
        return workerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_worker.worker_phone
     *
     * @param workerPhone the value for t_worker.worker_phone
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    public void setWorkerPhone(String workerPhone) {
        this.workerPhone = workerPhone == null ? null : workerPhone.trim();
    }
}