package com.whut.equipmanage.dao;

import com.whut.equipmanage.dataobject.AdminDO;

public interface AdminDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    int insert(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    int insertSelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    AdminDO selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    int updateByPrimaryKeySelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Tue Dec 15 15:04:24 CST 2020
     */
    int updateByPrimaryKey(AdminDO record);
}