package com.whut.equipmanage.dao;

import com.whut.equipmanage.dataobject.CheckDO;
import com.whut.equipmanage.dataobject.CheckDOKey;
import com.whut.equipmanage.dataobject.ProcessLogDO;

import java.util.List;

public interface CheckDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    int deleteByPrimaryKey(CheckDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    int insert(CheckDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    int insertSelective(CheckDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    CheckDO selectByPrimaryKey(CheckDOKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    int updateByPrimaryKeySelective(CheckDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_check
     *
     * @mbg.generated Thu Dec 17 19:15:34 CST 2020
     */
    int updateByPrimaryKey(CheckDO record);


    //查询全部作业记录
    List<CheckDO> commonQuery(int start, int limit);


    Integer getLogCount();
}