package com.whut.equipmanage.dao;

import com.whut.equipmanage.dataobject.DetailDO;

public interface DetailDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int insert(DetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int insertSelective(DetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    DetailDO selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int updateByPrimaryKeySelective(DetailDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_detail
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int updateByPrimaryKey(DetailDO record);
}