package com.whut.equipmanage.dao;

import com.whut.equipmanage.dataobject.EquipClassDO;

import java.util.List;

public interface EquipClassDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip_class
     *
     * @mbg.generated Mon Dec 14 18:00:41 CST 2020
     */
    int deleteByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip_class
     *
     * @mbg.generated Mon Dec 14 18:00:41 CST 2020
     */
    int insert(EquipClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip_class
     *
     * @mbg.generated Mon Dec 14 18:00:41 CST 2020
     */
    int insertSelective(EquipClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip_class
     *
     * @mbg.generated Mon Dec 14 18:00:41 CST 2020
     */
    EquipClassDO selectByPrimaryKey(Integer classId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip_class
     *
     * @mbg.generated Mon Dec 14 18:00:41 CST 2020
     */
    int updateByPrimaryKeySelective(EquipClassDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip_class
     *
     * @mbg.generated Mon Dec 14 18:00:41 CST 2020
     */
    int updateByPrimaryKey(EquipClassDO record);


    List<EquipClassDO> getEqupClasses();
}