package com.whut.equipmanage.dao;

import com.whut.equipmanage.dataobject.EquipDO;

import java.util.List;

public interface EquipDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip
     *
     * @mbg.generated Mon Dec 14 18:00:40 CST 2020
     */
    int deleteByPrimaryKey(Integer equipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip
     *
     * @mbg.generated Mon Dec 14 18:00:40 CST 2020
     */
    int insert(EquipDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip
     *
     * @mbg.generated Mon Dec 14 18:00:40 CST 2020
     */
    int insertSelective(EquipDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip
     *
     * @mbg.generated Mon Dec 14 18:00:40 CST 2020
     */
    EquipDO selectByPrimaryKey(Integer equipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip
     *
     * @mbg.generated Mon Dec 14 18:00:40 CST 2020
     */
    int updateByPrimaryKeySelective(EquipDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_equip
     *
     * @mbg.generated Mon Dec 14 18:00:40 CST 2020
     */
    int updateByPrimaryKey(EquipDO record);


    List<EquipDO> getEquipsByClassId(Integer classId);
}