package com.whut.equipmanage.dao;

import com.whut.equipmanage.dataobject.ProcessLogDO;

public interface ProcessLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_process_log
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_process_log
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int insert(ProcessLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_process_log
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int insertSelective(ProcessLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_process_log
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    ProcessLogDO selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_process_log
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int updateByPrimaryKeySelective(ProcessLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_process_log
     *
     * @mbg.generated Sun Dec 13 14:21:34 CST 2020
     */
    int updateByPrimaryKey(ProcessLogDO record);
}